version: '3.0'

services:
  send-api:
    container_name: send-api
    build:
      context: ./Comtek-project/sendapp  # Path to the directory containing the Dockerfile for sending data
    ports:
      - "3000:3000"  # Map the container's port 3000 to the host
    networks:
      - my-network

  get-api:
    container_name: get-api
    build:
      context: ./Comtek-project/getapp  # Path to the directory containing the Dockerfile for retrieving data
    ports:
      - "3001:3001"  # Map the container's port 3001 to the host
    networks:
      - my-network

networks:
  my-network:
    driver: bridge  # Use the bridge network driver
